const keys = {
  GET_LIST_HISTORY_CAMPAIGN: 'GET_LIST_HISTORY_CAMPAIGN',
  GET_DETAIL_BLOCK_HISTORY_CAMPAIGN: 'GET_DETAIL_BLOCK_HISTORY_CAMPAIGN',
  GET_LIST_ALL_CAMPAIGN: 'GET_LIST_ALL_CAMPAIGN',
  GET_LIST_FB_CARE_CAMPAIN: 'GET_LIST_FB_CARE_CAMPAIN',
  GET_DETAIL_CAMPAIGN_HISTORY: 'GET_DETAIL_CAMPAIGN_HISTORY',
  GET_DETAIL_CAMPAIGN_HISTORY_V2: 'GET_DETAIL_CAMPAIGN_HISTORY_V2',
  GET_DETAIL_CAMPAIGN_OF_UID_HISTORY: 'GET_DETAIL_CAMPAIGN_OF_UID_HISTORY',
}

export default keys
