const keys = {
  GET_LIST_APPELLATION: 'GET_LIST_APPELLATION',
  GET_INFO_APPELLATION: 'GET_INFO_APPELLATION',
  GET_LIST_GROUP_CREATED: 'GET_LIST_GROUP_CREATED',
  GET_LIST_GROUP_EXPLORED: 'GET_LIST_GROUP_EXPLORED',
  GET_LIST_GROUP_JOINED: 'GET_LIST_GROUP_JOINED',
  GET_INFO_GROUP: 'GET_INFO_GROUP',
  GET_ADDRESS: 'GET_ADDRESS',
  GET_MEMBERS_GROUP: 'GET_MEMBERS_GROUP',
  GET_LIST_REQUESTED_JOIN_GROUP: 'GET_LIST_REQUESTED_JOIN_GROUP',
  GET_LIST_REQUESTED_JOIN_GROUP_IN_GROUP:
    'GET_LIST_REQUESTED_JOIN_GROUP_IN_GROUP',
  GET_LIST_INVITED_JOIN_GROUP: 'GET_LIST_INVITED_JOIN_GROUP',
  GET_LIST_INVITED_JOIN_GROUP_IN_GROUP: 'GET_LIST_INVITED_JOIN_GROUP_IN_GROUP',
}

export default keys
