const keys = {
  LIST_EVENT: 'LIST_EVENT',
  LIST_TYPE_EVENT: 'LIST_TYPE_EVENT',
  LIST_PRIVACY_EVENT: 'LIST_PRIVACY_EVENT',
  LIST_FORMALITY_EVENT: 'LIST_FORMALITY_EVENT',
  DETAIL_EVENT: 'DETAIL_EVENT',
  LIST_PARTICIPANT_EVENT: 'LIST_PARTICIPANT_EVENT',
  STATISTIC_EVENT: 'STATISTIC_EVENT',
}

export default keys
