const keys = {
  LIST_USER_RIGHT_SIDEBAR: 'LIST_USER_RIGHT_SIDEBAR',
  GROUPS_CHAT: 'GROUPS_CHAT',
  ALL_MESSAGE_GROUP: 'ALL_MESSAGE_GROUP',
  INFORMATION_GROUP: 'INFORMATION_GROUP',
}

export default keys
