const GROUP_TYPE = {
  SET_GROUP_STATE_PRIVACY: 'SET_GROUP_STATE_PRIVACY',
  SET_GROUP_STATE_PRIVACY_ONLY_ME: 'SET_GROUP_STATE_PRIVACY_ONLY_ME',
  SET_GROUP_NAME: 'SET_GROUP_NAME',
}

export default GROUP_TYPE
