const keys = {
  BENEFITS: 'BENEFITS',
  OUTCOMES: 'OUTCOMES',
  COURSE_FOR: 'COURSE_FOR',
  INSTRUCTORS: 'INSTRUCTORS',
  SKILL_ACCQUIRED: 'SKILL_ACCQUIRED',

  LIST_COURSE: 'LIST_COURSE',
  INFO_COURSE: 'INFO_COURSE',
}

export default keys
