const type = {
  // step 1
  SETTING_SEND_EMAIL: 'SETTING_SEND_EMAIL',
  // step 2

  CHOOSE_LIB_EMAIL: 'CHOOSE_LIB_EMAIL',
  // step 3
  TYPE_ATTACHED_LINK: 'TYPE_ATTACHED_LINK',
  UPDATE_SEO_LINK_EXTERNAL: 'UPDATE_SEO_LINK_EXTERNAL',
  ADD_SEO_LINK_EXTERNAL: 'ADD_SEO_LINK_EXTERNAL',
  DELETE_SEO_LINK_EXTERNAL: 'DELETE_SEO_LINK_EXTERNAL',
  SEO_LINK_SYSTEM: 'SEO_LINK_SYSTEM',
  GET_SEO_LINK_SYSTEM: 'GET_SEO_LINK_SYSTEM',
  DELETE_SEO_LINK_SYSTEM: 'DELETE_SEO_LINK_SYSTEM',
}

export default type
