const keys = {
  LIST_BIZXU: 'LIST_BIZXU',
  DETAIL_BIZXU: 'DETAIL_BIZXU',
  LIST_BIZXU_TRANSACTION: 'LIST_BIZXU_TRANSACTION',
  CATEGORY_TRANSACTION: 'CATEGORY_TRANSACTION',
  TRANSACTION_TYPE: 'TRANSACTION_TYPE',
  TRANSACTION_STATUS: 'TRANSACTION_STATUS',
  STATISTIC_TOTAL_TRANSACTION: 'STATISTIC_TOTAL_TRANSACTION',
}

export default keys
