const keys = {
  GET_LIST_POST_BY_USER: 'GET_LIST_POST_BY_USER',
  GET_INFO_POST: 'GET_INFO_POST',
  GET_LIST_COMMENT: 'GET_LIST_COMMENT',
  CREATE_COMMENT: 'CREATE_COMMENT',
  GET_LIST_ALL_POST: 'GET_LIST_ALL_POST',
  GET_LIST_REPLY_COMMENT: 'GET_LIST_COMMENT',
  CREATE_REPLY_COMMENT: 'CREATE_COMMENT',
  GET_LIST_ALL_USER_POST: 'GET_LIST_ALL_USER_POST',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_LIST_GROUP_POST: 'GET_LIST_GROUP_POST',
  GET_STATISTIC_POST: 'GET_STATISTIC_POST',
}

export default keys
