const keys = {
  GET_STATISTIC_AUTOMATION: 'GET_STATISTIC_AUTOMATION',
  GET_BLOCK_TYPE_ACTION: 'GET_BLOCK_TYPE_ACTION',
  GET_BLOCK_TYPE_DECISION: 'GET_BLOCK_TYPE_DECISION',
  GET_BLOCK_TYPE_FB_ACTION: 'GET_BLOCK_TYPE_FB_ACTION',
  GET_LIST_AUTO_JOB: 'GET_LIST_AUTO_JOB',
  GET_LIST_AUTO_TASK: 'GET_LIST_AUTO_TASK',
  GET_LIST_ACCOUNT_FB: 'GET_LIST_ACCOUNT_FB',
  GET_LIST_EMAIL_TO_SEND_EMAIL: 'GET_LIST_EMAIL_TO_SEND_EMAIL',
  GET_LIST_LIBRARY_NOTIFICATION: 'GET_LIST_LIBRARY_NOTIFICATION',
  GET_LIST_STATUS_AUTOMATION: 'GET_LIST_STATUS_AUTOMATION',
  GET_LIST_PHONE_TO_SMS: 'GET_LIST_PHONE_TO_SMS',
  GET_LIST_TEMPLATE_SMS: 'GET_LIST_TEMPLATE_SMS',
  GET_LIST_SAMPLE_LIBARY: 'GET_LIST_SAMPLE_LIBARY',
  GET_LIST_COMMENT: 'GET_LIST_COMMENT',
  GET_LIST_AUTOJOB_SELECT: 'GET_LIST_AUTOJOB_SELECT',
  GET_STATISTIC_SALE_CAMPAIGN: 'GET_STATISTIC_SALE_CAMPAIGN',
  GET_DETAIL_CAMPAIGN: 'GET_DETAIL_CAMPAIGN',
  GET_LIST_DATA_FILTER: 'GET_LIST_DATA_FILTER',
  GET_LIST_DATA_FIELD_SALE_CAMPAIGN_AUTOMATION:
    'GET_LIST_DATA_FIELD_SALE_CAMPAIGN_AUTOMATION',
  GET_LIST_DATA_FIELD_FB_AUTOMATION: 'GET_LIST_DATA_FIELD_FB_AUTOMATION',
  GET_LIST_ACTION_AUTO_TASK_AUTOMATION: 'GET_LIST_ACTION_AUTO_TASK_AUTOMATION',
  GET_STATUS_CAMPAIGN: 'GET_STATUS_CAMPAIGN',
  GET_MEATADATA_WEBSITE: 'GET_MEATADATA_WEBSITE',
  GET_AUTOMATION_STATUS_APPROVE: 'GET_AUTOMATION_STATUS_APPROVE',
  GET_LIST_DATA_FILTER_AUTOMATION: 'GET_LIST_DATA_FILTER_AUTOMATION',

  GET_TEMPLATE_EMAIL: 'GET_TEMPLATE_EMAIL',
}

export default keys
