const keys = {
  GET_PROFILE_USER: 'GET_PROFILE_USER',
  GET_SOCIAL_LINK_USER: 'GET_SOCIAL_LINK_USER',
  GET_INFO_TO_CHANGE_PASSWORD_USER: 'GET_INFO_TO_CHANGE_PASSWORD_USER',
  GET_USERS_SYSTEM: 'GET_USERS_SYSTEM',
}
export default keys
