const keys = {
  LIST_CUSTOMER_LEAD_PROFILE_EXPLOITEDS:
    'LIST_CUSTOMER_LEAD_PROFILE_EXPLOITEDS',
  LIST_TAGS_CUSTOMER_LEAD: 'LIST_TAGS_CUSTOMER_LEAD',
  LIST_EDUCATION_OF_CUSTOMER_LEAD: 'LIST_EDUCATION_OF_CUSTOMER_LEAD',
  LIST_JOB_OF_CUSTOMER_LEAD: 'LIST_JOB_OF_CUSTOMER_LEAD',
  LIST_PLACES_LIVED_CUSTOMER_LEAD: 'LIST_PLACES_LIVED_CUSTOMER_LEAD',
  LIST_FUNNEL_ACTION_CUSTOMER_LEAD: 'LIST_FUNNEL_ACTION_CUSTOMER_LEAD',
  LIST_FUNNEL_OPERATOR_CUSTOMER_LEAD: 'LIST_FUNNEL_OPERATOR_CUSTOMER_LEAD',
  LIST_FUNNEL_CUSTOMER_LEAD: 'LIST_FUNNEL_CUSTOMER_LEAD',
  LIST_PROFILE_EXPLOITED_EXPORTS: 'LIST_PROFILE_EXPLOITED_EXPORTS',
  PROFILE_EXPLOITED_INFO: 'PROFILE_EXPLOITED_INFO',
  LIST_RELATIONSHIP: 'LIST_RELATIONSHIP',
  LIST_GROUP_FB: 'LIST_GROUP_FB',
  LIST_CUSTOMER_LEAD_ASSIGNED: 'LIST_CUSTOMER_LEAD_ASSIGNED',
  LIST_STATISTICS: 'LIST_STATISTICS',
}

export default keys
