export const data = {
  profile: {
    id: 1,
    url: '',
    username: 'Dominicushuy',
    fullname: 'Gia Huy',
    email: 'nlghuy@admin.com',
    short_bio: '',
    gender: 'Nam',
    phone: '0123321123',
    city: 'Vung tau',
    district: 'VT',
    wards: '',
    address: '',
    avatar: '',
    birthday: '',
    profession: '',
    age: '',
    socialLink: [
      {id: 1, url: '', type: 'facebook'},
      {id: 1, url: '', type: 'zalo'},
    ],
    bank_account: {name: 'NGUYEN LE GIA HUY', type: 'VIETCOMBANK', number: ''},
    c_follower: 2,
    c_following: 3,
    accumulated_point: 200000,
    accumulated_point_used: 50000,
  },
  myAddress: [
    {
      id: 1,
      phone: '0123321123',
      fullname: 'Nguyễn Huy',
      city: 'Vung tau',
      district: 'VT',
      wards: '',
      address: '',
      is_active: true,
    },
  ],
}
